### ISSUE TITLE
create build for production

### ISSUE THREAD

**Issue by lowenf** [superguigui/threejs-starter-kit#1]
hi! amazing build, really learned a lot from it :) Thanks so much!

I was wondering, how would one create a build ready to upload to production? Perhaps you have some sources for me or could add your workflow to the readme.md.

**Comment by superguigui** [comment]
Hi ! Thanks for your feedback :)
To build for production you need to run the script `npm run build` which will create minified index.js file in root folder. You can then upload index.html and index.js (+ any other asset you might use) on your servers and that should work.

You're right I should add more details about the build process in the README, i will get right on that :)

Let me know if build task works for you !

Also keep in mind that this starter is mainly for quick prototypes, I don't actually use it for client projects which often need more complex structures and tasks.

**Comment by lowenf** [comment]
thanks it worked! was there a way I could find out? Because I don't see a grunt file or smth similar. 

I want to use it for prototypes and just having fun creating and experimenting.. so it's perfect for that! Had some challenges because I wasn't used to all the import/export es6 stuff, but quickly learned.

you can see an example on xenochiku.com, I added audio and audio-reactivity to it (but there's no preloader yet so maybe give it a minute).

**Comment by superguigui** [comment]
For the tasks I'm using npm scripts so to see all the tasks available you should go see package.json https://github.com/superguigui/threejs-starter-kit/blob/master/package.json#L9
However If you are not used to npm scripts, the task in itself might not be very understandable so you were right to ask ;)
Good luck for your music visualization, I suggest you go dig into three.js/examples for inspiration.

**Comment by lowenf** [comment]
thanks man! Looking forward to any updates and the gui as well
