### ISSUE TITLE
html file for src / development

### ISSUE THREAD

**Issue by heaversm** [superguigui/threejs-starter-kit#5]
I need to have an html entry point in the `src` directory to add additional DOM components. How would I modify this setup for that? I see that HTMLWebpack is providing the HTML file for build / runtime, but how would I bypass that step?

Thank you for sharing this. Several things being used here I've never seen.

**Comment by superguigui** [comment]
Hi !
You could use the template option of HtmlWebpackPlugin for a custom html entry point:
```js
new HtmlWebpackPlugin({
    template: 'src/index.html', 
    title: isProd ? 'Production' : 'Development',
    meta: {/* ... */}
})
```
See the following for more details:
https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md
https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

Good luck ! Keep in mind however that this starter is designed for quick prototyping and might not be suitable for a whole project :)
